### ISSUE TITLE
Set up versioning

### ISSUE THREAD

**Issue by danielfc** [kalnee/trivor#107]
In order to make it publicly available, we must set up a versioning strategy via Gradle.

**Comment by danielfc** [comment]
https://github.com/researchgate/gradle-release (older, more stable)
or
https://github.com/nemerosa/versioning

**Comment by danielfc** [comment]
`gradle-release` doesn't seem to work very well for multi-projects. We may need to use a separate repo for trivor-sdk.

**Comment by danielfc** [comment]
@joaomcar do you think this would be a good idea? https://github.com/blog/2104-working-with-submodules

**Comment by joaomcar** [comment]
@danielfc, it doesn't work very well. I think a better approach would be a separate repo fro trivor-sdk.

**Comment by danielfc** [comment]
Not really useful to use these plugins, more trouble than help.
