### ISSUE TITLE
Publish SDK on Maven Central/JCenter

### ISSUE THREAD

**Issue by danielfc** [kalnee/trivor#108]
and/or Bintray JCenter

**Comment by danielfc** [comment]
Published on Bintray JCenter -> https://bintray.com/kalnee/maven/trivor-sdk

**Comment by danielfc** [comment]
it's not available on JCenter yet, will wait. Maybe there are other steps to take. For now, adding the following will make it possible to get the dependency:

```groovy
repositories {
	mavenCentral()
	jcenter {
		url "https://dl.bintray.com/kalnee/maven"
	}
}
```

**Comment by danielfc** [comment]
successfully published on JCenter -> https://bintray.com/kalnee/maven/trivor-sdk

it takes a while to be registered...

**Comment by joaomcar** [comment]
Nice :+1:
