### ISSUE TITLE
Define the responsibility of trivor-sdk

### ISSUE THREAD

**Issue by danielfc** [kalnee/trivor#84]
Answer the following questions:

Q. What is its purpose?
A. Generate language (EN) insights from .srt files (at first) by using Apache OpenNL. Be extensible enough to allow users to provide their own insight generators.

Q. What are the inputs?
A. Anything that makes it possible to get a subtitle content: `InputStream, URI (file://, s3://, http://)`

Q. What are the outputs?
A. Each insight (`Insight<T>`), all insights or default ones (`List<Insight>`). Insight over insights (`PostInsight<T>`).

Q. Should we keep it in the same repo?
A. I think so.

Q. What are its main dependencies?
A. Apache NLP, Amazon SDK (S3)

Q. Written in?
A. Java 8. Most of the code is already written in Java so there is no gain in using Kotlin or any other language.

**Comment by danielfc** [comment]
``` 
Input: InputStream, URI (file://, s3://, http://)
Flow: pre-process - identify sentences, tokens and tags - run insights generators
Output: Generic response? individual methods to get particular insights? Process each one individually?
```
First draft:

```java
    InsightProcessor ip = InsightsProcessor.Builder("s3://bucket/key").build();
    ip.isProcessed()
    ip.getPresentTense()
    ip.getFrequentNouns()
    ip.getCustomInsight(new MyInsightGenerator());
```

**Comment by danielfc** [comment]
@joaomcar please validate my answers in the description.

**Comment by joaomcar** [comment]
Answer the following questions:

Q. What is its purpose?
A. Generate language (EN) insights from .srt files (at first) by using Apache OpenNL. Be extensible enough to allow users to provide their own insight generators. :+1: 

Q. What are the inputs?
A. Anything that makes it possible to get a subtitle content: InputStream, URI (file://, s3://, http://) :+1: 

Q. What are the outputs?
A. Each insight (Insight<T>), all insights or default ones (List<Insight>). Insight over insights (PostInsight<T>). :+1: 

Q. Should we keep it in the same repo?
A. I think so. _At first I think it's a good idea. We can review this later if we deem necessary._

Q. What are its main dependencies?
A. Apache NLP, Amazon SDK (S3). _I think Amazon SDK isn't a dependency for our SDK. It should work in a standalone manner. Why do you consider Amazon SDK a dependency?_

Q. Written in?
A. Kotlin 1.1.2 :+1:

**Comment by danielfc** [comment]
```
Q. What are its main dependencies?
A. Apache NLP, Amazon SDK (S3). I think Amazon SDK isn't a dependency for our SDK. It should work in a standalone manner. Why do you consider Amazon SDK a dependency?
```

As explained offline, I think it's a good idea to allow users to use the S3 namespace (`s3://`) to download .srt files from AWS S3.
